database:
  path: "reabilitacao.db"

protocolo:
  fases:
    - id: 1
      nome: "Fase 1 - Proteção"
    - id: 2
      nome: "Fase 2 - Mobilidade"
    - id: 3
      nome: "Fase 3 - Força"
    - id: 4
      nome: "Fase 4 - Potência"
    - id: 5
      nome: "Fase 5 - Retorno ao Esporte" 